# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setEnabled(True)
        self.play_button.setGeometry(QtCore.QRect(120, 350, 121, 71))
        self.play_button.setObjectName("play_button")
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setGeometry(QtCore.QRect(320, 350, 131, 71))
        self.pause_button.setObjectName("pause_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(520, 350, 121, 71))
        self.stop_button.setObjectName("stop_button")
        self.volume_slider = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider.setGeometry(QtCore.QRect(710, 120, 22, 241))
        self.volume_slider.setMaximum(100)
        self.volume_slider.setOrientation(QtCore.Qt.Vertical)
        self.volume_slider.setObjectName("volume_slider")
        self.progress_slider = QtWidgets.QSlider(self.centralwidget)
        self.progress_slider.setGeometry(QtCore.QRect(210, 460, 341, 22))
        self.progress_slider.setOrientation(QtCore.Qt.Horizontal)
        self.progress_slider.setObjectName("progress_slider")
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setGeometry(QtCore.QRect(120, 50, 121, 71))
        self.open_button.setObjectName("open_button")
        self.song_label = QtWidgets.QLabel(self.centralwidget)
        self.song_label.setGeometry(QtCore.QRect(250, 190, 211, 81))
        self.song_label.setObjectName("song_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play_button.setText(_translate("MainWindow", "开始"))
        self.pause_button.setText(_translate("MainWindow", "暂停"))
        self.stop_button.setText(_translate("MainWindow", "停止"))
        self.open_button.setText(_translate("MainWindow", "打开"))
        self.song_label.setText(_translate("MainWindow", "TextLabel"))
